<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>
      <parent>
            <groupId>com.lzh</groupId>
            <artifactId>seckill</artifactId>
            <version>0.0.1-SNAPSHOT</version>
      </parent>

      <artifactId>common</artifactId>
      <packaging>jar</packaging>

      <dependencies>
            <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
            </dependency>
            <dependency>
                  <groupId>org.projectlombok</groupId>
                  <artifactId>lombok</artifactId>
            </dependency>
            <dependency>
                  <groupId>cn.hutool</groupId>
			<artifactId>hutool-all</artifactId>
            </dependency>
            <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-databind</artifactId>
            </dependency>
            <!-- 处理jdk8日期格式化问题 -->
            <dependency>
                  <groupId>com.fasterxml.jackson.datatype</groupId>
                  <artifactId>jackson-datatype-jsr310</artifactId>
            </dependency>
            <dependency>
                  <groupId>com.alibaba</groupId>
                  <artifactId>druid-spring-boot-3-starter</artifactId>
            </dependency>
      </dependencies>
</project>