server:
  port: 8847

logging:
  level:
    root: info

spring:
  profiles:
    include:
    - common
  application:
    name: nacos-config
  cloud:
    nacos:
      server-addr: ${docker.service.nacos}:8848
  config:
    import:
    - nacos:nacos-config-example.properties?refreshEnabled=true