appendonly yes
requirepass redis123456

# lazy free
lazyfree-lazy-eviction no
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
replica-lazy-flush yes
lazyfree-lazy-user-del yes
lazyfree-lazy-user-flush yes

# memory
maxmemory 1GB
maxmemory-policy volatile-ttl